name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter version
        run: flutter --version

      - name: Pub get
        run: flutter pub get

      # Tidak gagal kalau ada file belum ter-format
      - name: Format check (non-fatal)
        run: |
          CHANGED=$(dart format --output=none --set-exit-if-changed .; echo $?)
          if [ "$CHANGED" = "0" ]; then
            echo "Format OK"
          else
            echo "Format changed; not failing CI."
          fi

      # Gunakan DART ANALYZE dan jangan fatal utk info/warning
      - name: Analyze (non-fatal infos & warnings)
        run: dart analyze --no-fatal-infos --no-fatal-warnings
